source(allowSchemaDrift: true,
	validateSchema: false,
	inferDriftedColumnTypes: true,
	ignoreNoFilesFound: false,
	format: 'parquet') ~> source1
source(allowSchemaDrift: true,
	validateSchema: false,
	ignoreNoFilesFound: false,
	format: 'parquet') ~> source2
split1@validos derive(hra_intento1 = iif(isNull(hra_intento1), '00:00:00', toString(byName('hra_intento1'))),
		motivo_fallo_cod = coalesce(motivo_fallo_cod, 'No especificado'),
		resultado_intento1 = coalesce(resultado_intento1, 'Sin intento')) ~> handleNulls
MapDrifted2 aggregate(groupBy(tip_paquete,
		id_remitente,
		cond_id,
		id_zona_destino,
		peso_kg,
		fec_recepcion,
		hra_recepcion,
		fec_entrega_programada,
		fec_intento1,
		hra_intento1,
		resultado_intento1,
		fec_intento2,
		hra_intento2,
		resultado_intento2,
		fec_entrega_real,
		estado_final,
		motivo_fallo_cod,
		vr_declarado),
	id_envio = first(id_envio)) ~> aggregate1
source1 derive(id_envio = toLong(byName('id_envio')),
		id_remitente = toLong(byName('id_remitente')),
		cond_id = toLong(byName('cond_id')),
		id_zona_destino = toLong(byName('id_zona_destino')),
		tip_paquete = toString(byName('tip_paquete')),
		peso_kg = toDouble(byName('peso_kg')),
		fec_recepcion = toString(byName('fec_recepcion')),
		hra_recepcion = toString(byName('hra_recepcion')),
		fec_entrega_programada = toString(byName('fec_entrega_programada')),
		fec_intento1 = toString(byName('fec_intento1')),
		hra_intento1 = toString(byName('hra_intento1')),
		resultado_intento1 = toString(byName('resultado_intento1')),
		fec_intento2 = toString(byName('fec_intento2')),
		hra_intento2 = toString(byName('hra_intento2')),
		resultado_intento2 = toString(byName('resultado_intento2')),
		fec_entrega_real = toString(byName('fec_entrega_real')),
		estado_final = toString(byName('estado_final')),
		motivo_fallo_cod = toString(byName('motivo_fallo_cod')),
		vr_declarado = toDouble(byName('vr_declarado'))) ~> MapDrifted2
source2 derive(nomb_cond = toString(byName('nomb_cond')),
		apell_cond = toString(byName('apell_cond')),
		tip_doc = toString(byName('tip_doc')),
		num_doc_hash = toString(byName('num_doc_hash')),
		fec_ingreso = toString(byName('fec_ingreso')),
		id_ciudad_base = toString(byName('id_ciudad_base')),
		tip_vehiculo = toString(byName('tip_vehiculo')),
		cod_zona_asignada = toLong(byName('cod_zona_asignada')),
		activo = toLong(byName('activo')),
		calific_promedio_acum = toDouble(byName('calific_promedio_acum')),
		cond_id = toLong(byName('cond_id'))) ~> MapDrifted3
aggregate1, MapDrifted3 join(aggregate1@cond_id == MapDrifted3@cond_id,
	joinType:'left',
	matchType:'exact',
	ignoreSpaces: false,
	broadcast: 'auto')~> join1
join1 select(mapColumn(
		tip_paquete,
		id_remitente,
		cond_id_tms = aggregate1@cond_id,
		id_zona_destino,
		peso_kg,
		fec_recepcion,
		hra_recepcion,
		fec_entrega_programada,
		fec_intento1,
		hra_intento1,
		resultado_intento1,
		fec_intento2,
		hra_intento2,
		resultado_intento2,
		fec_entrega_real,
		estado_final,
		motivo_fallo_cod,
		vr_declarado,
		id_envio,
		nomb_cond,
		apell_cond,
		tip_doc,
		num_doc_hash,
		fec_ingreso,
		id_ciudad_base,
		tip_vehiculo,
		cod_zona_asignada,
		activo,
		calific_promedio_acum,
		cond_id_dim = MapDrifted3@cond_id
	),
	skipDuplicateMapInputs: true,
	skipDuplicateMapOutputs: true) ~> select1
select1 split(not(isNull(cond_id_dim)),
	isNull(cond_id_dim),
	disjoint: false) ~> split1@(validos, invalidos)
handleNulls select(mapColumn(
		tip_paquete,
		id_remitente,
		cond_id = cond_id_tms,
		id_zona_destino,
		peso_kg,
		fec_recepcion,
		hra_recepcion,
		fec_entrega_programada,
		fec_intento1,
		hra_intento1,
		resultado_intento1,
		fec_intento2,
		hra_intento2,
		resultado_intento2,
		fec_entrega_real,
		estado_final,
		motivo_fallo_cod,
		vr_declarado,
		id_envio
	),
	skipDuplicateMapInputs: true,
	skipDuplicateMapOutputs: true) ~> select2
select2 sink(allowSchemaDrift: true,
	validateSchema: false,
	format: 'parquet',
	partitionFileNames:['data.parquet'],
	umask: 0022,
	preCommands: [],
	postCommands: [],
	skipDuplicateMapInputs: true,
	skipDuplicateMapOutputs: true,
	partitionBy('hash', 1)) ~> sink1
split1@invalidos sink(allowSchemaDrift: true,
	validateSchema: false,
	format: 'parquet',
	partitionFileNames:['errors.parquet'],
	umask: 0022,
	preCommands: [],
	postCommands: [],
	skipDuplicateMapInputs: true,
	skipDuplicateMapOutputs: true,
	partitionBy('hash', 1)) ~> sink2