source(allowSchemaDrift: true,
	validateSchema: false,
	inferDriftedColumnTypes: true,
	ignoreNoFilesFound: false,
	format: 'parquet') ~> source1
MapDrifted1 aggregate(groupBy(nom_zona,
		id_ciudad,
		barrio_referencia,
		latitud_centroide,
		longitud_centroide,
		nivel_trafico_prom,
		tip_zona,
		distancia_bodega_km),
	id_zona = first(id_zona)) ~> aggregate1
aggregate1 derive(nivel_trafico_prom = coalesce(nivel_trafico_prom, 'Medio'),
		nom_zona = sha2(256, coalesce(nom_zona, ''))) ~> derivedColumn1
source1 derive(id_zona = toLong(byName('id_zona')),
		nom_zona = toString(byName('nom_zona')),
		id_ciudad = toString(byName('id_ciudad')),
		barrio_referencia = toString(byName('barrio_referencia')),
		latitud_centroide = toDouble(byName('latitud_centroide')),
		longitud_centroide = toDouble(byName('longitud_centroide')),
		nivel_trafico_prom = toString(byName('nivel_trafico_prom')),
		tip_zona = toString(byName('tip_zona')),
		distancia_bodega_km = toDouble(byName('distancia_bodega_km'))) ~> MapDrifted1
derivedColumn1 sink(allowSchemaDrift: true,
	validateSchema: false,
	format: 'parquet',
	partitionFileNames:['data.parquet'],
	umask: 0022,
	preCommands: [],
	postCommands: [],
	skipDuplicateMapInputs: true,
	skipDuplicateMapOutputs: true,
	partitionBy('hash', 1)) ~> sink1