source(allowSchemaDrift: true,
	validateSchema: false,
	inferDriftedColumnTypes: true,
	ignoreNoFilesFound: false,
	format: 'parquet') ~> source1
source(allowSchemaDrift: true,
	validateSchema: false,
	inferDriftedColumnTypes: true,
	ignoreNoFilesFound: false,
	format: 'parquet') ~> source2
source1 derive(nomb_cond = toString(byName('nomb_cond')),
		apell_cond = toString(byName('apell_cond')),
		tip_doc = toString(byName('tip_doc')),
		num_doc_hash = toString(byName('num_doc_hash')),
		fec_ingreso = toString(byName('fec_ingreso')),
		id_ciudad_base = toString(byName('id_ciudad_base')),
		tip_vehiculo = toString(byName('tip_vehiculo')),
		cod_zona_asignada = toLong(byName('cod_zona_asignada')),
		activo = toLong(byName('activo')),
		calific_promedio_acum = toDouble(byName('calific_promedio_acum')),
		cond_id = toLong(byName('cond_id'))) ~> MapDrifted1
source2 derive(tip_paquete = toString(byName('tip_paquete')),
		id_remitente = toLong(byName('id_remitente')),
		cond_id = toLong(byName('cond_id')),
		id_zona_destino = toLong(byName('id_zona_destino')),
		peso_kg = toDouble(byName('peso_kg')),
		fec_recepcion = toString(byName('fec_recepcion')),
		hra_recepcion = toString(byName('hra_recepcion')),
		fec_entrega_programada = toString(byName('fec_entrega_programada')),
		fec_intento1 = toString(byName('fec_intento1')),
		hra_intento1 = toString(byName('hra_intento1')),
		resultado_intento1 = toString(byName('resultado_intento1')),
		fec_intento2 = toString(byName('fec_intento2')),
		hra_intento2 = toString(byName('hra_intento2')),
		resultado_intento2 = toString(byName('resultado_intento2')),
		fec_entrega_real = toString(byName('fec_entrega_real')),
		estado_final = toString(byName('estado_final')),
		motivo_fallo_cod = toString(byName('motivo_fallo_cod')),
		vr_declarado = toDouble(byName('vr_declarado')),
		id_envio = toLong(byName('id_envio'))) ~> MapDrifted2
MapDrifted1 aggregate(groupBy(cond_id),
	total_reg = count(1),
		nulos_calific = sum(iif(isNull(calific_promedio_acum), 1, 0))) ~> aggregate1
MapDrifted2 aggregate(groupBy(cond_id),
	total_reg = count(1),
		nulos_hra_intento1 = sum(iif(isNull(hra_intento1), 1, 0)),
		nulos_motivo_fallo = sum(iif(isNull(motivo_fallo_cod), 1, 0))) ~> aggregate2
aggregate1 derive(pct_nulos_calific = (nulos_calific * 100) / total_reg,
		tabla = 'OPE_CONDUCTORES') ~> derivedColumn1
aggregate2 derive(pct_nulos_hra_intento = (nulos_hra_intento1 * 100) / total_reg,
		pct_nulos_motivo_fallo = (nulos_motivo_fallo * 100) / total_reg,
		tabla = 'TMS_ENVIOS') ~> derivedColumn2
derivedColumn1, derivedColumn2 union(byName: true)~> union1
union1 select(mapColumn(
		cond_id,
		tabla,
		total_reg,
		nulos_calific,
		pct_nulos_calific,
		nulos_hra_intento1,
		nulos_motivo_fallo,
		pct_nulos_hra_intento,
		pct_nulos_motivo_fallo
	),
	skipDuplicateMapInputs: true,
	skipDuplicateMapOutputs: true) ~> select1
select1 sink(allowSchemaDrift: true,
	validateSchema: false,
	partitionFileNames:['data.csv'],
	umask: 0022,
	preCommands: [],
	postCommands: [],
	skipDuplicateMapInputs: true,
	skipDuplicateMapOutputs: true,
	partitionBy('hash', 1)) ~> sink1